import type { Metadata } from 'next';
import React from 'react';

import { Inter as FontSans } from 'next/font/google';

import './globals.css';
import FloatingMenu from '@/components/withFloatingMenu';
import { cn } from '@/lib/utils';
import dynamic from 'next/dynamic';

const Provider = dynamic(() => import('@/components/provider'), { ssr: false });

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <Provider>
          <header className="fixed  left-0 top-0 z-50 w-full  px-2 py-4 md:top-8">
            <FloatingMenu>
              {Array(4)
                .fill('_')
                .map((_, i) => (
                  <div key={i}>{i}</div>
                ))}
            </FloatingMenu>
          </header>
          {children}
        </Provider>
      </body>
    </html>
  );
}
